### PR TITLE
docs(LICENSE): copyright is for full life of Algolia

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by julienbourdeau** [comment]
I'm not pushing this files to the repos yet, do you think it should be updated on all repositories? Should the starting date change depending on when the project was started?

**Comment by Haroenv** [comment]
IANAL, but I think Vincent is right, since this is the way that FB writes their licenses

**Comment by vvo** [comment]
> I'm not pushing this files to the repos yet, do you think it should be updated on all repositories? Should the starting date change depending on when the project was started?

We should push the LICENSE and no it doesn't matter when the exact project started I guess #almostALawyer

**Comment by julienbourdeau** [comment]
Ok I will add it 👌 Thanks you both! (Currently this file was not pushed to repos).

**Pull request merged**
