### PR TITLE
docs(maintainers): add js client

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Review by Haroenv — APPROVED** [review]

**Comment by julienbourdeau** [comment]
Currently, I don't update the JS client because you already have contributing doc and github template. Do you only want the MAINTAINERS.md?

Also, feel free to add more that 2 maintainers if necessary.

**Comment by Haroenv** [comment]
There’s only two maintainers :)

**Comment by vvo** [comment]
> Currently, I don't update the JS client because you already have contributing doc and github template. Do you only want the MAINTAINERS.md?

We want to be like all other clients ultimately so consider us the same, so there's no exceptions to the processes

**Comment by julienbourdeau** [comment]
🆗 great!
I'll improve the `CONTRIBUTING.md` to add more language specific stuff before I open PRs on the js client.

**Pull request merged**
